blank_issues_enabled: false
contact_links:
  - name: 📖 Contribution Guide
    url: https://github.com/orpheusdark/pull-request-practice/blob/main/README.md
    about: Please read the guide before submitting an issue.
